name: Dev CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          apt-get update
          apt-get install -y nginx php8.2-cli php8.2-fpm php8.2-curl php8.2-xml composer
      - name: Configure and start services
        run: |
          sed -i "s|root /var/www/html;|root $GITHUB_WORKSPACE;|" /etc/nginx/sites-available/default
          service php8.2-fpm start
          service nginx start
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Lint PHP files
        run: find . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Run Codeception tests
        run: vendor/bin/codecept run --skip-group php83
      - name: Check server logs for PHP warnings
        run: |
          if grep -E 'PHP (Warning|Notice)' /var/log/nginx/error.log; then
            echo 'PHP warnings detected'
            cat /var/log/nginx/error.log
            exit 1
          fi
