name: Dev CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          apt-get update
          apt-get install -y nginx php8.2-cli php8.2-fpm php8.2-curl php8.2-xml composer
      - name: Configure and start services
        run: |
          cat <<CONF > /etc/nginx/sites-available/default
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root $GITHUB_WORKSPACE;
              index index.php index.html index.htm;
              server_name _;
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.2-fpm.sock;
              }
              location ~ /\.ht {
                  deny all;
              }
          }
          CONF
          service php8.2-fpm start
          service nginx start
      - name: Composer install
        run: composer install
      - name: Lint PHP files
        run: find . -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Run Codeception tests
        run: vendor/bin/codecept run acceptance --skip-group php83
