name: Dev CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP CLI
        run: |
          apt-get update
          apt-get install -y php8.2-cli
      - name: Lint PHP files
        run: find . -name '*.php' -print0 | xargs -0 -n1 php -l

  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: debian:12
    strategy:
      matrix:
        run-codeception: [true]
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          apt-get update
          apt-get install -y nginx php8.2-cli php8.2-fpm php8.2-curl \
            php8.2-xml composer curl golang
      - name: Configure and start services
        run: |
          cat <<CONF > /etc/nginx/sites-available/default
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root $GITHUB_WORKSPACE;
              index index.php index.html index.htm;
              server_name _;
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.2-fpm.sock;
              }
              location ~ /\.ht {
                  deny all;
              }
          }
          CONF
          service php8.2-fpm start
          service nginx start
      - name: Start Go API
        run: |
          git clone --depth 1 \
            https://github.com/davestj/ternary-fission-reactor.git \
            /tmp/ternary-fission-reactor
          cd /tmp/ternary-fission-reactor/src/go
          cat <<'EOF' > ../../configs/test.conf
          api_port=8080
          ssl_enabled=false
          EOF
          go run api.ternary.fission.server.go -config ../../configs/test.conf &
      - name: Start mock Reactor
        run: |
          sed -i \
            's|reactor_base_url=.*|reactor_base_url=http://127.0.0.1:9999|' \
            /tmp/ternary-fission-reactor/configs/ternary_fission.conf
          python3 - <<'PY' &
            from http.server import BaseHTTPRequestHandler, HTTPServer
            import json
            class Handler(BaseHTTPRequestHandler):
                def do_GET(self):
                    self.send_response(200)
                    self.send_header('Content-Type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({'status': 'ok'}).encode())
            HTTPServer(('127.0.0.1',9999), Handler).serve_forever()
          PY
      - name: Wait for Go API
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:8080/ > /dev/null; then
              exit 0
            fi
            sleep 1
          done
          exit 1
      - name: Composer install
        run: composer install
      - name: Run Codeception tests
        if: matrix.run-codeception
        run: vendor/bin/codecept run acceptance --skip-group php83
